// <auto-generated />
using System;
using AcciTransito.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcciTransito.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211001163331_Inicial4")]
    partial class Inicial4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AcciTransito.App.Dominio.Entidades.Accidente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AgenteTransitoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCoordenadasid")
                        .HasColumnType("int");

                    b.Property<string>("NumeroAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peritaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Personaid")
                        .HasColumnType("int");

                    b.Property<int?>("Vehiculosid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("AgenteTransitoId");

                    b.HasIndex("IdCoordenadasid");

                    b.HasIndex("Personaid");

                    b.HasIndex("Vehiculosid");

                    b.ToTable("Accidente");
                });

            modelBuilder.Entity("AcciTransito.App.Dominio.Entidades.AgenteTransito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroAgente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCelular")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AgenteTransito");
                });

            modelBuilder.Entity("AcciTransito.App.Dominio.Entidades.Coordenadas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("Latitud")
                        .HasColumnType("real");

                    b.Property<float>("Longitud")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Coordenadas");
                });

            modelBuilder.Entity("AcciTransito.App.Dominio.Entidades.Genero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NombreGenero")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("AcciTransito.App.Dominio.Entidades.Personas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Generoid")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCelular")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Generoid");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("AcciTransito.App.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("LicenciaTransito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Personaid")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Personaid");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("AcciTransito.App.Dominio.Entidades.Accidente", b =>
                {
                    b.HasOne("AcciTransito.App.Dominio.Entidades.AgenteTransito", "AgenteTransito")
                        .WithMany()
                        .HasForeignKey("AgenteTransitoId");

                    b.HasOne("AcciTransito.App.Dominio.Entidades.Coordenadas", "IdCoordenadas")
                        .WithMany()
                        .HasForeignKey("IdCoordenadasid");

                    b.HasOne("AcciTransito.App.Dominio.Entidades.Personas", "Persona")
                        .WithMany()
                        .HasForeignKey("Personaid");

                    b.HasOne("AcciTransito.App.Dominio.Entidades.Vehiculo", "Vehiculos")
                        .WithMany()
                        .HasForeignKey("Vehiculosid");

                    b.Navigation("AgenteTransito");

                    b.Navigation("IdCoordenadas");

                    b.Navigation("Persona");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("AcciTransito.App.Dominio.Entidades.Personas", b =>
                {
                    b.HasOne("AcciTransito.App.Dominio.Entidades.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("Generoid");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("AcciTransito.App.Dominio.Entidades.Vehiculo", b =>
                {
                    b.HasOne("AcciTransito.App.Dominio.Entidades.Personas", "Persona")
                        .WithMany()
                        .HasForeignKey("Personaid");

                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
